# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `catalog_name`")
spark.sql("USE SCHEMA `schema_name`")

# COMMAND ----------

spark.sql("SELECT count(*) FROM <catalog_name>.<schema_name>.orders_raw")
